string(REPLACE ":" ";" roots "${WORKER_ROOTS}")
set(offenders "")
foreach(root IN LISTS roots)
    file(GLOB_RECURSE sources "${root}/*.hpp" "${root}/*.cpp" "${root}/*.cppm")
    foreach(source IN LISTS sources)
        file(STRINGS "${source}" hits REGEX "#[ \t]*include[ \t]*[\"<]snf/(server|runtime)/")
        if(hits)
            list(APPEND offenders "${source}: ${hits}")
        endif()
    endforeach()
endforeach()
if(offenders)
    string(REPLACE ";" "\n  " report "${offenders}")
    message(FATAL_ERROR "The worker runtime must not depend on the legacy runtime:\n  ${report}")
endif()
message(STATUS "Worker layer is clean")
